### ISSUE TITLE
System.Runtime.InteropServices.COMException (0x80070721): A security package specific error occurred.

### ISSUE THREAD

**Issue by konghv** [Dec0ne/KrbRelayUp#31]
Hello
Did anyone fix this issue?

PS C:\Users\normaluser\Desktop\kbrrelayUp_Debug\Debug> .\KrbRelayUp.exe relay -Domain local.domain -CreateNewComputerAccount -ComputerName fake6$ -ComputerPassword 123456$
KrbRelayUp - Relaying you to SYSTEM

[+] Rewriting function table
[+] Rewriting PEB
[+] Init COM server
[+] Computer account "fake6$" added with password "123456$"
[+] Register COM server
[+] Forcing SYSTEM authentication
[+] Got Krb Auth from NT/SYSTEM. Relying to LDAP now...
[+] LDAP session established
[-] LDAP connection failed
System.Runtime.InteropServices.COMException (0x80070721): A security package specific error occurred.

A security package specific error occurred.

   at KrbRelayUp.Relay.Ole32.CoGetInstanceFromIStorage(COSERVERINFO pServerInfo, Guid& pclsid, Object pUnkOuter, CLSCTX dwClsCtx, IStorage pstg, UInt32 cmq, MULTI_QI[] rgmqResults)
   at KrbRelayUp.Relay.Relay.Run() in C:\Users\admin.DESKTOP-8OHJG6I\Desktop\TMP\KrbRelayUp-main\KrbRelayUp\Relay\Relay.cs:line 159

**Comment by bestrocker221** [comment]
Having same problem

**Comment by wwwGeneral** [comment]
Same here, I believe I have default configuration

**Comment by strishin** [comment]
Has anyone found a solution for this problem?

**Comment by wwwGeneral** [comment]
> Has anyone found a solution for this problem?

It seems that KrbRelayUp.exe have been fixed in october 2022 with the possibility of create LDAP bind with DCOM.
(tell me if i'm wrong)
Source: https://twitter.com/_Imm0/status/1583187655222706177 (the whole discussion)

**Comment by jannlemm0913** [comment]
For anyone playing around with the code and encountering this error: I get this error when I try to use an SPN with a specified port in it. Has most likely nothing to do with the issue encountered in the posts above, but if you google the error code, you might find this post.

**Comment by Startr4ck** [comment]
> > Has anyone found a solution for this problem?有没有人找到这个问题的解决方案？
> 
> It seems that KrbRelayUp.exe have been fixed in october 2022 with the possibility of create LDAP bind with DCOM.KrbRelayUp.exe 似乎已于 2022 年 10 月修复，可以使用 DCOM 创建 LDAP 绑定。 (tell me if i'm wrong) （如果我错了请告诉我） Source: https://twitter.com/_Imm0/status/1583187655222706177 (the whole discussion) 来源：https://twitter.com/_Imm0/status/1583187655222706177（整个讨论）

Yes,After 2022.11.8 Patch . KrbRelayUp  dead ,anyone read this can give up now.

**Comment by Startr4ck** [comment]
> > Has anyone found a solution for this problem?
> 
> It seems that KrbRelayUp.exe have been fixed in october 2022 with the possibility of create LDAP bind with DCOM. (tell me if i'm wrong) Source: https://twitter.com/_Imm0/status/1583187655222706177 (the whole discussion)
Yes,After 2022.11.8 Patch . KrbRelayUp dead ,anyone read this can give up now.

**Comment by KeyStrOke95** [comment]
I gave up 😢
